# Generated by Django 2.1 on 2020-05-16 21:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('referrals', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='flatreferral',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='flatreferral',
            name='referred',
        ),
        migrations.RemoveField(
            model_name='flatreferral',
            name='referrer',
        ),
        migrations.DeleteModel(
            name='FlatReferral',
        ),
    ]
