# Generated by Django 2.1 on 2020-05-16 22:23

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('referrals', '0002_auto_20200516_2242'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MultiLevelReferral',
            new_name='Referral',
        ),
    ]
