# Generated by Django 2.1 on 2020-05-17 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('referrals', '0003_auto_20200516_2323'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='referral',
            table='referral',
        ),
    ]
