# Generated by Django 2.1 on 2020-05-17 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referrals', '0004_auto_20200517_1214'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='referral_id',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
