# Generated by Django 2.1 on 2020-05-21 16:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('referrals', '0006_auto_20200521_1635'),
    ]

    operations = [
        migrations.AddField(
            model_name='referral',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
