# Generated by Django 2.1 on 2020-05-30 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referrals', '0007_referral_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
