# Generated by Django 2.1 on 2020-06-15 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referrals', '0008_link_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='referral',
            name='has_paid_activation',
            field=models.BooleanField(default=False),
        ),
    ]
