# Generated by Django 2.1 on 2020-06-26 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referrals', '0011_auto_20200625_2333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referral',
            name='path',
            field=models.CharField(max_length=99000000),
        ),
    ]
