# Generated by Django 2.1 on 2020-09-21 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referrals', '0012_auto_20200626_0004'),
    ]

    operations = [
        migrations.AddField(
            model_name='referral',
            name='package',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
