# Generated by Django 2.1 on 2020-08-22 11:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categorys', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Enter the name of the product', max_length=120)),
                ('slug', models.SlugField(blank=True, help_text='Leave blank for the system to generate', unique=True)),
                ('description', models.TextField(help_text='Enter the product full desciption')),
                ('regular_price', models.DecimalField(decimal_places=2, default=39.99, help_text='Enter the product prize', max_digits=20)),
                ('sales_price', models.DecimalField(blank=True, decimal_places=2, help_text='sales prize shoud be less than regular prize', max_digits=20, null=True)),
                ('stock_status', models.CharField(choices=[('In stock', 'In stock'), ('Out of stock', 'Out of stock'), ('On backorder', 'On backorder')], help_text='Select product stock status', max_length=120)),
                ('quantity_stocked', models.SmallIntegerField(default=0, help_text='Enter the quantity of product in stock')),
                ('delivery_location', models.TextField(blank=True, max_length=300, null=True)),
                ('featured', models.BooleanField(default=False)),
                ('date_to_featured', models.CharField(blank=True, max_length=50)),
                ('active', models.BooleanField(default=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(blank=True, help_text='Select product category', null=True, on_delete=django.db.models.deletion.CASCADE, to='categorys.Category')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
