# Generated by Django 2.1 on 2020-08-23 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20200823_1638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='stock_status',
            field=models.CharField(blank=True, choices=[('In stock', 'In stock'), ('Out of stock', 'Out of stock'), ('On backorder', 'On backorder')], help_text='Select product stock status', max_length=120),
        ),
        migrations.AlterField(
            model_name='product',
            name='title',
            field=models.CharField(blank=True, help_text='Enter the name of the product', max_length=120),
        ),
    ]
